# Generated by Django 5.0.7 on 2024-07-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateField(),
        ),
    ]
