# Generated by Django 4.2.7 on 2024-02-22 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(verbose_name='Sighting Date')),
                ('location', models.CharField(choices=[('ATL', 'Atlantic Ocean'), ('PAC', 'Pacific Ocean'), ('IND', 'Indian Ocean'), ('ARC', 'Arctic Ocean'), ('SOU', 'Southern Ocean'), ('CAR', 'Carribean Sea'), ('PHI', 'Philippine Sea'), ('COR', 'Coral Sea'), ('MED', 'Mediterranean Sea'), ('MEX', 'Gulf Of Mexico')], default='ATL', max_length=3)),
                ('octopus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.octopus')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
