# Generated by Django 4.2.7 on 2024-02-23 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_sighting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('octopus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.octopus')),
            ],
        ),
    ]
