# Generated by Django 4.2.7 on 2024-03-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_photo_url_photo_created_at_photo_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': 'Photos'},
        ),
    ]
