# Generated by Django 4.2.7 on 2024-04-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_photo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='location',
            field=models.CharField(choices=[('ATL', 'Atlantic Ocean'), ('PAC', 'Pacific Ocean'), ('IND', 'Indian Ocean'), ('ARC', 'Arctic Ocean'), ('SOU', 'Southern Ocean'), ('CAR', 'Carribean Sea'), ('PHI', 'Philippine Sea'), ('COR', 'Coral Sea'), ('MED', 'Mediterranean Sea'), ('MEX', 'Gulf Of Mexico'), ('THA', 'Gulf Of Thailand'), ('BEN', 'Bay Of Bengal'), ('JAV', 'Java Sea'), ('RED', 'Red Sea')], default='ATL', max_length=3),
        ),
    ]
