# Generated by Django 5.0.6 on 2024-07-11 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('octopus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(choices=[('Atlantic Ocean', 'Atlantic Ocean'), ('Pacific Ocean', 'Pacific Ocean'), ('Indian Ocean', 'Indian Ocean'), ('Arctic Ocean', 'Arctic Ocean'), ('Southern Ocean', 'Southern Ocean'), ('Carribean Sea', 'Carribean Sea'), ('Philippine Sea', 'Philippine Sea'), ('Coral Sea', 'Coral Sea'), ('Mediterranean Sea', 'Mediterranean Sea'), ('Gulf of Mexico', 'Gulf of Mexico'), ('Gulf of Thailand', 'Gulf of Thailand'), ('Bay of Bengal', 'Bay of Bengal'), ('Java Sea', 'Java Sea'), ('Red Sea', 'Red Sea')], max_length=50)),
                ('octopus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='octopus.octopus')),
                ('sighting_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
