# Generated by Django 5.0.6 on 2024-07-01 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('octopus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('octopus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octopus.octopus')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
