# Generated by Django 5.0.6 on 2024-07-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_sighting_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='owner',
            new_name='sighting_owner',
        ),
    ]
