# Generated by Django 5.0.6 on 2024-07-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_rename_owner_sighting_sighting_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='location',
            field=models.CharField(choices=[('Atlantic Ocean', 'Atlantic Ocean'), ('Pacific Ocean', 'Pacific Ocean'), ('Indian Ocean', 'Indian Ocean'), ('Arctic Ocean', 'Arctic Ocean'), ('Southern Ocean', 'Southern Ocean'), ('Carribean Sea', 'Carribean Sea'), ('Philippine Sea', 'Philippine Sea'), ('Coral Sea', 'Coral Sea'), ('Mediterranean Sea', 'Mediterranean Sea'), ('Gulf of Mexico', 'Gulf of Mexico'), ('Gulf of Thailand', 'Gulf of Thailand'), ('Bay of Bengal', 'Bay of Bengal'), ('Java Sea', 'Java Sea'), ('Red Sea', 'Red Sea')], max_length=50),
        ),
    ]
